# Generated by Django 2.2.6 on 2019-10-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20191028_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='looking_for_job',
            field=models.BooleanField(default=True),
        ),
    ]
