# Generated by Django 2.2.6 on 2019-10-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_cohort_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='screenshot',
            field=models.ImageField(null=True, upload_to='project_screenshots/'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='user_avatars/'),
        ),
    ]
