# Generated by Django 2.2.6 on 2019-11-01 15:15

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_auto_20191030_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='end_date',
            field=models.DateField(default=datetime.date(2019, 11, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='looking_for_job',
            field=models.BooleanField(default=True, verbose_name='Are you currently looking for a job?'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(check=models.Q(start_date__lte=django.db.models.expressions.F('end_date')), name='start_date_lte_end_date'),
        ),
    ]
