# Generated by Django 2.2.6 on 2019-10-31 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_auto_20191030_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fans',
            field=models.ManyToManyField(blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='looking_for_job',
            field=models.BooleanField(default=True, verbose_name='Are you currently looking for a job?'),
        ),
    ]
