# Generated by Django 2.2.6 on 2019-11-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_auto_20191101_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohort',
            options={'ordering': ['-end_date']},
        ),
    ]
